### ISSUE TITLE
Project 1 Feedback

### ISSUE THREAD

**Issue by ParnalPatil** [airavata-courses/Zilean#48]
Hi Zilean Team,

First up, amazing work in setting up the entire application within the short deadline. The UI is looking good and it's very easy to maneuver to different pages with very less waiting time. The microservice architecture is well made and precise which makes it easy to understand the flow. However, there are still certain areas of improvement that you can make in the application. You could add pagination where the logs are visible which will make it easy for users go through their logs instead of having to scroll down continuously. Also, we can see request and response in the audit logs which will not be very easy to understand for the normal user and will seem alien to him. But apart from this, the application looks great and I'm quite eager to see how you enhance and improve it in the next phase!

**Comment by RushikeshPharate** [comment]
Thanks for the feedback @ParnalPatil ,

For pagination, we have implemented the backend logic in both audit and requests-history microservices but we were not able to implement that feature on the frontend because of time constraints. We will definitely implement it in the next sprint. 

Also, for the audit logs, we are planning to add an actions column in the next sprint which will store the action that led to the entry in the DB and display that on UI.

Thanks for the feedback, appreciate it :)

**Comment by impiyush83** [comment]
Thanks for the feedback 👍🏻  

@ParnalPatil  Added the task linked to this issue.

https://github.com/airavata-courses/Zilean/issues/49
